// Classificação dos alunos Everest aprovados/convocados no CIAAR.
// Fonte: exports/aprovados (app-everest). Ordenado por média final (desc).
// media = 0 indica nota não divulgada (renderizar como "—").

export type AprovadoEAOF = {
  nome: string;
  especialidade: string;
  media: number;
  categoria: "convocado" | "aprovado";
};

export const aprovadosEAOF2026: AprovadoEAOF[] = [
  { nome: "CARLOS EDUARDO CESAR COSTA", especialidade: "COM", media: 9.43, categoria: "convocado" },
  { nome: "GIORDANE DE SOUZA LIMA", especialidade: "COM", media: 9.27, categoria: "convocado" },
  { nome: "ALEX TEIXEIRA DE FREITAS", especialidade: "COM", media: 9.12, categoria: "convocado" },
  { nome: "DOUGLAS LEÃO", especialidade: "COM", media: 8.77, categoria: "convocado" },
  { nome: "WILLIAM DO NASCIMENTO FERREIRA", especialidade: "COM", media: 8.65, categoria: "convocado" },
  { nome: "JOSÉ JAILSON DO NASCIMENTO", especialidade: "COM", media: 8.58, categoria: "convocado" },
  { nome: "JOSÉ RIBEIRO DA COSTA JÚNIOR", especialidade: "COM", media: 8.53, categoria: "convocado" },
  { nome: "FREDSON ALVES DE FARIA", especialidade: "COM", media: 8.42, categoria: "convocado" },
  { nome: "THENÓRIO ALMEIDA LOPES DE ARAÚJO", especialidade: "COM", media: 8.35, categoria: "convocado" },
  { nome: "REGINALDO QUINTANILHA JOSÉ", especialidade: "COM", media: 8.33, categoria: "convocado" },
  { nome: "LEANDRO TIBIRISSÁ CHEFFER", especialidade: "COM", media: 8.3, categoria: "convocado" },
  { nome: "JOSE EDUARDO DOS SANTOS SALES", especialidade: "COM", media: 8.18, categoria: "convocado" },
  { nome: "ROBSON RIBAS DE GOIS", especialidade: "COM", media: 8.15, categoria: "convocado" },
  { nome: "ALAN TEIXEIRA REIS", especialidade: "COM", media: 8.12, categoria: "convocado" },
  { nome: "FÁBIO DOS SANTOS LIMA", especialidade: "ANV", media: 8.08, categoria: "convocado" },
  { nome: "LUCIANO BURITI DO NASCIMENTO", especialidade: "COM", media: 8.07, categoria: "convocado" },
  { nome: "JOSEIAS MUNIZ DA SILVA", especialidade: "COM", media: 7.98, categoria: "convocado" },
  { nome: "JAILSON DE ARAÚJO MEDEIROS", especialidade: "COM", media: 7.92, categoria: "convocado" },
  { nome: "ALBERTO PEREIRA PINTO FILHO", especialidade: "COM", media: 7.87, categoria: "convocado" },
  { nome: "ELIAS AMARO DOS SANTOS JUNIOR", especialidade: "ANV", media: 7.87, categoria: "convocado" },
  { nome: "MARCELO SANTOS PACHECO", especialidade: "COM", media: 7.85, categoria: "convocado" },
  { nome: "RODRIGO MARCELINO MONTEIRO", especialidade: "ANV", media: 7.85, categoria: "convocado" },
  { nome: "ERALDO MENEZES DA SILVA", especialidade: "COM", media: 7.78, categoria: "convocado" },
  { nome: "JORGE CARDOSO PALHETA", especialidade: "COM", media: 7.78, categoria: "convocado" },
  { nome: "ALEXANDRE VARGAS CHAVES", especialidade: "COM", media: 7.77, categoria: "convocado" },
  { nome: "GILSOMAR DE OLIVEIRA THOMAZ", especialidade: "COM", media: 7.72, categoria: "convocado" },
  { nome: "CARLOS RODRIGO DE SOUSA", especialidade: "COM", media: 7.68, categoria: "convocado" },
  { nome: "ALCIR DE SOUZA BAPTISTA", especialidade: "COM", media: 7.67, categoria: "convocado" },
  { nome: "GLEIDSON DE SOUZA SOARES", especialidade: "COM", media: 7.63, categoria: "convocado" },
  { nome: "RHODSON BARROS MACEDO", especialidade: "COM", media: 7.62, categoria: "convocado" },
  { nome: "CLÁUDIO GONÇALVES DE ALBUQUERQUE SILVA", especialidade: "COM", media: 7.6, categoria: "convocado" },
  { nome: "ALEXANDRE PASSOS BALDERRAMAS", especialidade: "COM", media: 7.57, categoria: "convocado" },
  { nome: "EDIMILSON BRAZ LIMA", especialidade: "COM", media: 7.55, categoria: "convocado" },
  { nome: "RICARDO FELIPE GUILHERME", especialidade: "COM", media: 7.55, categoria: "convocado" },
  { nome: "MOISES NOGUEIRA XAVIER", especialidade: "COM", media: 7.53, categoria: "convocado" },
  { nome: "PABLO DOS SANTOS ABREU", especialidade: "COM", media: 7.53, categoria: "convocado" },
  { nome: "CLAUDIO URUGUAY FARIA", especialidade: "COM", media: 7.43, categoria: "convocado" },
  { nome: "INALDO RIBEIRO DA SILVA", especialidade: "COM", media: 7.35, categoria: "convocado" },
  { nome: "ARMANDO HENRIQUE LOPES CORRÊA", especialidade: "COM", media: 7.32, categoria: "convocado" },
  { nome: "ROGERIO MACHADO DA SILVA", especialidade: "COM", media: 7.28, categoria: "convocado" },
  { nome: "ALZIMAR SOBREIRA", especialidade: "COM", media: 7.25, categoria: "convocado" },
  { nome: "WAGNER DA SILVA DE FARIAS", especialidade: "COM", media: 7.2, categoria: "convocado" },
  { nome: "ANDRE MAURÍCIO GOMES CAVALCANTI", especialidade: "COM", media: 7.13, categoria: "convocado" },
  { nome: "RODRIGO PERES CARDOSO", especialidade: "COM", media: 7.13, categoria: "convocado" },
  { nome: "GUSTAVO SANTOS DE SOUZA", especialidade: "COM", media: 7.12, categoria: "convocado" },
  { nome: "JOSINALDO MIRANDA ALVES", especialidade: "COM", media: 7.08, categoria: "convocado" },
  { nome: "MARCELO SILVA DE OLIVEIRA", especialidade: "COM", media: 7.05, categoria: "convocado" },
  { nome: "MARIO BENEDITO DOS SANTOS MAIA", especialidade: "COM", media: 7.03, categoria: "convocado" },
  { nome: "JOZILAINE DA SILVA OLIVEIRA VIEIRA", especialidade: "COM", media: 6.97, categoria: "convocado" },
  { nome: "PAULO ROBERTO PINHEIRO GUERRA", especialidade: "ANV", media: 6.97, categoria: "convocado" },
  { nome: "ALEXANDRE SALLES BIANNA", especialidade: "COM", media: 6.95, categoria: "convocado" },
  { nome: "ANDERSON MIRANDA CARNEIRO", especialidade: "COM", media: 6.83, categoria: "convocado" },
  { nome: "JOÃO BATISTA SILVA GUSMÃO", especialidade: "COM", media: 6.78, categoria: "convocado" },
  { nome: "KASSIO GERALDO FERREIRA", especialidade: "COM", media: 6.77, categoria: "convocado" },
  { nome: "PATRÍCIA CRISTINA FONTES SOUSA", especialidade: "COM", media: 6.75, categoria: "convocado" },
  { nome: "EMERSON MAXWELL MARCIANO PEDRONI SILVA", especialidade: "COM", media: 6.72, categoria: "convocado" },
  { nome: "WELLINGTON MENDES DE CARVALHO", especialidade: "COM", media: 6.7, categoria: "convocado" },
  { nome: "WELLINGTON TARGINO DA SILVA", especialidade: "COM", media: 6.67, categoria: "convocado" },
  { nome: "ADEILSON MANUEL SOARES", especialidade: "COM", media: 6.63, categoria: "aprovado" },
  { nome: "CRISPINIANA DE SOUZA CRUZ RAPOSO", especialidade: "COM", media: 6.63, categoria: "convocado" },
  { nome: "LUCIANO GOMES DE MELLO", especialidade: "COM", media: 6.63, categoria: "convocado" },
  { nome: "MARCELINO RODRIGO SARAIVA", especialidade: "COM", media: 6.53, categoria: "convocado" },
  { nome: "BERGSON TOMAZ E SILVA", especialidade: "COM", media: 6.47, categoria: "convocado" },
  { nome: "HUGO AURÉLIO MOREIRA BERNER", especialidade: "COM", media: 6.47, categoria: "convocado" },
  { nome: "FRANCISCO ADRIANO LEMOS BARBOSA", especialidade: "COM", media: 6.45, categoria: "convocado" },
  { nome: "RONNIERY MARTINS DE ALMEIDA", especialidade: "ANV", media: 6.45, categoria: "convocado" },
  { nome: "ROGÉRIO MARX FERREIRA", especialidade: "COM", media: 6.35, categoria: "convocado" },
  { nome: "CLEBER LUÍS CORRÊIA", especialidade: "COM", media: 6.33, categoria: "convocado" },
  { nome: "JOAN JOSÉ RODRIGUES DA SILVA", especialidade: "COM", media: 6.33, categoria: "convocado" },
  { nome: "SEBASTIÃO VIRGÍNIO FILHO", especialidade: "COM", media: 6.2, categoria: "convocado" },
  { nome: "MARCELO DIAS DE PAULA LIMA", especialidade: "COM", media: 6.15, categoria: "convocado" },
  { nome: "ANDRÉ LUIZ BRITO ANDRÉ", especialidade: "COM", media: 6.13, categoria: "convocado" },
  { nome: "FRANCISCO PAULO DUARTE LIMA", especialidade: "COM", media: 5.95, categoria: "aprovado" },
  { nome: "BLEIFORD DINELYS LEONARDO", especialidade: "COM", media: 5.92, categoria: "aprovado" },
  { nome: "CLEITON BANUS DA SILVA", especialidade: "ANV", media: 5.92, categoria: "aprovado" },
  { nome: "FRANCELIR PEREIRA LOPES", especialidade: "COM", media: 5.8, categoria: "aprovado" },
  { nome: "ANDERSON DOS SANTOS COSTA", especialidade: "COM", media: 5.77, categoria: "aprovado" },
  { nome: "RAFAEL TEJADA SCHLEE", especialidade: "COM", media: 5.77, categoria: "aprovado" },
  { nome: "LUIS ALFREDO DE CAMPOS LISBOA", especialidade: "COM", media: 5.75, categoria: "aprovado" },
  { nome: "NARA LUANA XAVIER DA SILVA FERREIRA", especialidade: "COM", media: 5.75, categoria: "aprovado" },
  { nome: "LUIZ FABIANO WIETHAN QUINHONES", especialidade: "ANV", media: 5.67, categoria: "aprovado" },
  { nome: "RAFAEL DA SILVA ARAUJO", especialidade: "COM", media: 5.67, categoria: "aprovado" },
  { nome: "ROBSON DRUMOND DA SILVA", especialidade: "ANV", media: 5.37, categoria: "aprovado" },
  { nome: "TARCÍSIO EMMANUEL DE BARROS MEDEIROS", especialidade: "COM", media: 0, categoria: "convocado" },
];

export const totalAprovadosEAOF2026 = aprovadosEAOF2026.length;
export const totalConvocadosEAOF2026 = aprovadosEAOF2026.filter((a) => a.categoria === "convocado").length;
